version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: wdo_leads
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    # Don't expose database port to external network for security
    expose:
      - "5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD:-postgres123}@db:5432/wdo_leads
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      PORT: 3001
      # Trust Cloudflare proxy
      TRUST_PROXY: "true"
      # CORS configuration for Cloudflare
      CORS_ORIGIN: ${CORS_ORIGIN:-https://yourdomain.com}
    networks:
      - app-network
    volumes:
      - ./backend/uploads:/app/uploads
    expose:
      - "3001"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      # Set the API URL for production
      VITE_API_URL: ${VITE_API_URL:-https://yourdomain.com/api}
    networks:
      - app-network
    expose:
      - "80"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      # Only expose port 80 since Cloudflare handles HTTPS
      - "80:80"
    volumes:
      - ./nginx-cloudflare.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    environment:
      # Nginx worker configuration for production
      NGINX_WORKER_PROCESSES: auto
      NGINX_WORKER_CONNECTIONS: 1024
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 